name: OhPHF
options:
  bundleIdPrefix: com.ohphf
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 2
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_NSCameraUsageDescription: "Camera access is needed for document scanning"
    INFOPLIST_KEY_CFBundleDisplayName: "oh! PHF"

targets:
  OhPHF:
    type: application
    platform: iOS
    sources:
      - OhPHF
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ohphf.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 63JMX4D777
